### ISSUE TITLE
Parametricity link in README doesn't go anywhere

### ISSUE THREAD

**Issue by philwills** [non/alleycats#2]
I was intrigued by the discussion of parametric reasoning for Sets, but the link with the name 'parametricity' doesn't go anywhere.

**Comment by non** [comment]
Oops! Good catch, thanks! I'll try to remember which resource I was going to link.

**Comment by non** [comment]
I ended up linking to an essay by @S11001001: http://failex.blogspot.jp/2013/06/fake-theorems-for-free.html

I think this is the best treatment of the issue that is approachable to readers without Haskell experience.

**Comment by philwills** [comment]
Thanks, that's useful to my understanding.
