### ISSUE TITLE
Bring back support for Scala 2.10

### ISSUE THREAD

**Issue by adelbertc** [non/alleycats#3]
Seems we had dropped it in alleycats since we weren't publishing 2.10 snapshots for Cats. Since (I think) we have a 2.10 jar published for Cats 0.1.2, we can perhaps re-instate 2.10 support here? :-)

**Comment by non** [comment]
I've re-added support for cross-building for Scala 2.10.

Sorry for just pushing commits. From here on out I'll follow our PR model.
