### ISSUE TITLE
Publish alleycats

### ISSUE THREAD

**Issue by non** [non/alleycats#4]
When should we do this?

Also, should we sync up alleycats version numbers with Cats'? If so, we should start with 0.1.2.

**Comment by philwills** [comment]
As a potential consumer, I'd definitely vote for keeping version numbers in sync.

**Comment by non** [comment]
Yeah, it makes sense to me too.

Let's plan to do this. There's an outside possibility that Alleycats might need a critical bug fix which has to go out before Cats can be released, but we can cross that bridge when we come to it.

**Comment by milessabin** [comment]
I can spend some time on this today ... what needs doing?

**Comment by non** [comment]
The only thing I know that needs to be fixed is snapshot publishing.

**Comment by non** [comment]
(And of course more documentation, laws, and tests would be good too.)

**Comment by non** [comment]
Just released 0.1.2! Will update the README and close this issue for now.
